server:
  port: 8080
  compression:
    enabled: false
logging:
  level:
    com.brageast.project.webmessage: DEBUG
spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webmessage?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 200075xzh