server:
  port: 80
  compression:
    enabled: true
#logging:
#  level:
#    com.brageast.project.webmessage: DEBUG
spring:
  thymeleaf:
    cache: true
#  jpa:
#    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver