mybatis:
  mapper-locations: classpath*:/mybatis/*Mapper.xml
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    check-template: false
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: rest
  mvc:
    static-path-pattern: /static/**